spring:
  # log color 출력
  output:
    ansi:
      enabled: always
  # h2 데이터 베이스 설정
  h2:
    console:
      enabled: true
  # JDBC 설정
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: